development:
  adapter: postgresql
  encoding: unicode
  database: tea_time_development
  pool: 5
  username: alankrumholz
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: tea_time_test
  pool: 5
  username: alankrumholz
  password:
  timeout: 5000